stages:
  etl:
    cmd: python etlpipeline.py data/data2.csv
    deps:
    - data/data2.csv
    - etlpipeline.py
    outs:
    - data/data5.csv
  
  split:
    cmd: python traintest.py data/data5.csv
    deps:
    - data/data5.csv
    - traintest.py
    outs:
    - finalized_model1.pkl
    - feature1.pkl

  # webapp:
  #   cmd: python app.py finalized_model1.pkl feature1.pkl
  #   deps:
  #   - finalized_model1.pkl
  #   - feature1.pkl
  #   - app.py
