stages:
  split:
    cmd: python train-test.py data/data3.csv
    deps:
    - data/data3.csv
    - train-test.py
    outs:
    - finalized_model1.pkl
    - feature1.pkl

  # webapp:
  #   cmd: python app.py finalized_model1.pkl feature1.pkl
  #   deps:
  #   - finalized_model1.pkl
  #   - feature1.pkl
  #   - app.py
